import { IPost } from "../types";

export const blog: IPost[] = [
  {
    id: 1,
    slug: "sprzatanie-mieszkan-prywatnych-czy-warto-zatrudnic-osobe-do-sprzatania",
    title:"Sprzątanie mieszkań prywatnych - czy warto zatrudnić osobę do sprzątania.",
    description:"Na co zwrócić uwagę zamawiając sprzątanie mieszkań prywatnie?",
    text:"Sprzątanie mieszkań prywatnie to usługa, dzięki której Twoje wnętrze będzie piękne, czyste i pachnące. Nasza ekipa sprzątająca zadba o to, aby wszystkie trudnodostępne zakamarki zostały starannie wysprzątane. Posiadamy nowoczesny sprzęt czyszczący i korzystamy tylko ze sprawdzonych i skutecznych środków czystości. Zamawiając sprzątanie mieszkań prywatnych, dokładnie określ swoje potrzeby, a my dołożymy wszelkich starań, aby przywrócić Twoim meblom, podłogom i oknom dawny blask.",
    date:"30.10.2022",
    double:"https://mdbootstrap.com/img/new/standard/nature/182.jpg",
  },
  {
    id: 2,
    slug: "jak-serwis-sprzatajacy-moze-wplynac-pozytywnie-na-komfort-twojego-zycia",
    title:"Sprzątanie mieszkań prywatnych - czy warto zatrudnić osobę do sprzątania.",
    description:"Na co zwrócić uwagę zamawiając sprzątanie mieszkań prywatnie?",
    text:"Sprzątanie mieszkań prywatnie to usługa, dzięki której Twoje wnętrze będzie piękne, czyste i pachnące. Nasza ekipa sprzątająca zadba o to, aby wszystkie trudnodostępne zakamarki zostały starannie wysprzątane. Posiadamy nowoczesny sprzęt czyszczący i korzystamy tylko ze sprawdzonych i skutecznych środków czystości. Zamawiając sprzątanie mieszkań prywatnych, dokładnie określ swoje potrzeby, a my dołożymy wszelkich starań, aby przywrócić Twoim meblom, podłogom i oknom dawny blask.",
    date:"30.10.2022",
    double:"https://mdbootstrap.com/img/new/standard/nature/182.jpg",
  },
  {
    id: 3,
    slug: "/sprzatanie-po-imprezie-to-dla-ciebie-istny-koszmar-zatrudnij-profesjonalistow-od-cleanwhale",
    title:"Sprzątanie mieszkań prywatnych - czy warto zatrudnić osobę do sprzątania.",
    description:"Na co zwrócić uwagę zamawiając sprzątanie mieszkań prywatnie?",
    text:"Sprzątanie mieszkań prywatnie to usługa, dzięki której Twoje wnętrze będzie piękne, czyste i pachnące. Nasza ekipa sprzątająca zadba o to, aby wszystkie trudnodostępne zakamarki zostały starannie wysprzątane. Posiadamy nowoczesny sprzęt czyszczący i korzystamy tylko ze sprawdzonych i skutecznych środków czystości. Zamawiając sprzątanie mieszkań prywatnych, dokładnie określ swoje potrzeby, a my dołożymy wszelkich starań, aby przywrócić Twoim meblom, podłogom i oknom dawny blask.",
    date:"30.10.2022",
    double:"https://mdbootstrap.com/img/new/standard/nature/182.jpg",
  },
  {
    id: 4,
    slug: "poznaj-sprawdzone-metody-na-to-jak-pozbyc-sie-kurzu-we-wlasnym-domu",
    title:"Sprzątanie mieszkań prywatnych - czy warto zatrudnić osobę do sprzątania.",
    description:"Na co zwrócić uwagę zamawiając sprzątanie mieszkań prywatnie?",
    text:"Sprzątanie mieszkań prywatnie to usługa, dzięki której Twoje wnętrze będzie piękne, czyste i pachnące. Nasza ekipa sprzątająca zadba o to, aby wszystkie trudnodostępne zakamarki zostały starannie wysprzątane. Posiadamy nowoczesny sprzęt czyszczący i korzystamy tylko ze sprawdzonych i skutecznych środków czystości. Zamawiając sprzątanie mieszkań prywatnych, dokładnie określ swoje potrzeby, a my dołożymy wszelkich starań, aby przywrócić Twoim meblom, podłogom i oknom dawny blask.",
    date:"30.10.2022",
    double:"https://mdbootstrap.com/img/new/standard/nature/182.jpg",
  },
  {
    id: 5,
    slug: "jak-sprzatac-mieszkanie-po-remoncie-proste-kroki-do-idealnej-czystosci",
    title:"Sprzątanie mieszkań prywatnych - czy warto zatrudnić osobę do sprzątania.",
    description:"Na co zwrócić uwagę zamawiając sprzątanie mieszkań prywatnie?",
    text:"Sprzątanie mieszkań prywatnie to usługa, dzięki której Twoje wnętrze będzie piękne, czyste i pachnące. Nasza ekipa sprzątająca zadba o to, aby wszystkie trudnodostępne zakamarki zostały starannie wysprzątane. Posiadamy nowoczesny sprzęt czyszczący i korzystamy tylko ze sprawdzonych i skutecznych środków czystości. Zamawiając sprzątanie mieszkań prywatnych, dokładnie określ swoje potrzeby, a my dołożymy wszelkich starań, aby przywrócić Twoim meblom, podłogom i oknom dawny blask.",
    date:"30.10.2022",
    double:"https://mdbootstrap.com/img/new/standard/nature/182.jpg",
  },
  {
    id: 6,
    slug: "jak-wyczyscic-pralke-wszystko-co-musisz-wiedziec",
    title:"Sprzątanie mieszkań prywatnych - czy warto zatrudnić osobę do sprzątania.",
    description:"Na co zwrócić uwagę zamawiając sprzątanie mieszkań prywatnie?",
    text:"Sprzątanie mieszkań prywatnie to usługa, dzięki której Twoje wnętrze będzie piękne, czyste i pachnące. Nasza ekipa sprzątająca zadba o to, aby wszystkie trudnodostępne zakamarki zostały starannie wysprzątane. Posiadamy nowoczesny sprzęt czyszczący i korzystamy tylko ze sprawdzonych i skutecznych środków czystości. Zamawiając sprzątanie mieszkań prywatnych, dokładnie określ swoje potrzeby, a my dołożymy wszelkich starań, aby przywrócić Twoim meblom, podłogom i oknom dawny blask.",
    date:"30.10.2022",
    double:"https://mdbootstrap.com/img/new/standard/nature/182.jpg",
  },
  {
    id: 7,
    slug: "czyszczenie-piekarnika-dlaczego-warto-i-jak-czesto-powinno-sie-to-robic",
    title:"Sprzątanie mieszkań prywatnych - czy warto zatrudnić osobę do sprzątania.",
    description:"Na co zwrócić uwagę zamawiając sprzątanie mieszkań prywatnie?",
    text:"Sprzątanie mieszkań prywatnie to usługa, dzięki której Twoje wnętrze będzie piękne, czyste i pachnące. Nasza ekipa sprzątająca zadba o to, aby wszystkie trudnodostępne zakamarki zostały starannie wysprzątane. Posiadamy nowoczesny sprzęt czyszczący i korzystamy tylko ze sprawdzonych i skutecznych środków czystości. Zamawiając sprzątanie mieszkań prywatnych, dokładnie określ swoje potrzeby, a my dołożymy wszelkich starań, aby przywrócić Twoim meblom, podłogom i oknom dawny blask.",
    date:"30.10.2022",
    double:"https://mdbootstrap.com/img/new/standard/nature/182.jpg",
  },
  {
    id: 8,
    slug: "ile-kosztuje-prasowanie-koszul-cennik-na-godziny",
    title:"Sprzątanie mieszkań prywatnych - czy warto zatrudnić osobę do sprzątania.",
    description:"Na co zwrócić uwagę zamawiając sprzątanie mieszkań prywatnie?",
    text:"Sprzątanie mieszkań prywatnie to usługa, dzięki której Twoje wnętrze będzie piękne, czyste i pachnące. Nasza ekipa sprzątająca zadba o to, aby wszystkie trudnodostępne zakamarki zostały starannie wysprzątane. Posiadamy nowoczesny sprzęt czyszczący i korzystamy tylko ze sprawdzonych i skutecznych środków czystości. Zamawiając sprzątanie mieszkań prywatnych, dokładnie określ swoje potrzeby, a my dołożymy wszelkich starań, aby przywrócić Twoim meblom, podłogom i oknom dawny blask.",
    date:"30.10.2022",
    double:"https://mdbootstrap.com/img/new/standard/nature/182.jpg",
  },
];
